runtime: java8
basic_scaling:
  max_instances: 2
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'calvincs262-fall2018-teama.appspot.com'
api_version: '1.0'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional
